### 1-Install and import required libraries

In [1]:
!pip install nibabel

In [2]:
import numpy as np
import nibabel as nb
import pandas as pd
from google.colab import files
import os
import csv 

### Import niftii files from github

In [3]:
!git clone https://github.com/theibsi/data_sets.git

Cloning into 'data_sets'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 11267 (delta 6), reused 40 (delta 6), pack-reused 11226
Receiving objects: 100% (11267/11267), 563.05 MiB | 15.24 MiB/s, done.
Resolving deltas: 100% (1295/1295), done.
Checking out files: 100% (10332/10332), done.


In [4]:
data_path = 'data_sets/ibsi_1_digital_phantom/nifti'
!ls
mask_data = nb.load(os.path.join(data_path, 'mask', 'mask.nii.gz')).get_fdata()
phantom_data = nb.load(os.path.join(data_path, 'image', 'phantom.nii.gz')).get_fdata()

data_sets  sample_data


#### Note that it is also possible to import data from local by using files.upload as below

In [5]:
# upload images
# uploaded = files.upload()

In [6]:
# upload masks
# files.upload()

In [7]:
# mask_data = nb.load('mask.nii.gz').get_fdata()
# phantom_data = nb.load('phantom.nii.gz').get_fdata()

#### some sanity checks

In [8]:
#verifying the shape of mask and phantom are similar
mask_data.shape == phantom_data.shape


True

In [9]:
# compute the phantom with the mask 
phantom_masked = phantom_data * mask_data

# checking
print(np.unique(mask_data))
print(np.unique(phantom_data))
print(np.unique(phantom_masked))

[0. 1.]
[1. 3. 4. 6. 9.]
[0. 1. 3. 4. 6.]


In [10]:
phantom_masked

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [4., 0., 1., 1.],
        [4., 4., 1., 1.]],

       [[4., 4., 4., 4.],
        [4., 1., 1., 1.],
        [1., 1., 1., 1.],
        [4., 4., 1., 1.]],

       [[4., 4., 4., 4.],
        [6., 6., 1., 1.],
        [6., 3., 0., 1.],
        [6., 6., 6., 6.]],

       [[1., 1., 0., 0.],
        [1., 1., 1., 1.],
        [4., 1., 1., 1.],
        [4., 1., 1., 1.]],

       [[1., 1., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#### Compute features and store values into a dictionnary where each key correponds to the current feature name

In [11]:
features_dict = {}
# mean intensity
features_dict['mean_intensity'] = phantom_masked.flatten().mean()
print(features_dict['mean_intensity'])

1.9875


In [12]:
#calculate mean variance
features_dict['intensity_variance'] = ((phantom_masked - features_dict['mean_intensity'])**2).mean()
features_dict['intensity_variance']

3.1373437500000003

In [13]:
# Intensity skewness
num = ((phantom_data - features_dict['mean_intensity'])**2).mean()
denom = features_dict['intensity_variance']**1.5
features_dict['intensity_skewness']= num / denom 
features_dict['intensity_skewness']

0.6328408108841197

In [14]:
# intensity kurtosis
num = ((phantom_masked - features_dict['mean_intensity'])**4).mean()
denom = features_dict['intensity_variance']**2 
features_dict['intensity kurtosis'] = (num / denom) - 3
features_dict['intensity kurtosis'] 

-0.18175094675151637

In [15]:
#Median intensity
features_dict['median_intensity'] = np.median(phantom_masked.flatten())
features_dict['median_intensity']

1.0

In [16]:
#minimum intensity
features_dict['min_intensity'] = (phantom_masked.flatten()).min()
features_dict['min_intensity']

0.0

In [17]:
# the 10th percentile
features_dict['tenth_percentile'] = np.percentile(phantom_masked.flatten(), 10)
features_dict['tenth_percentile']

1.0

In [18]:
# the 90 percentile
features_dict['ninetenth_percentile'] = np.percentile(phantom_masked.flatten(), 90)
features_dict['ninetenth_percentile']

4.0

In [19]:
# maximum intensity
features_dict['max_intensity'] = phantom_masked.flatten().max()
features_dict['max_intensity']

6.0

In [20]:
# intensity interquartile range
features_dict['interquartile_range'] = np.percentile(phantom_masked.flatten(), 75) - np.percentile(phantom_masked.flatten(), 25)
features_dict['interquartile_range']

3.0

In [21]:
# intensity range
features_dict['intensity range'] = features_dict['max_intensity'] - features_dict['min_intensity']
features_dict['intensity range']

6.0

In [22]:
# intensity-based-mean absolute deviation
features_dict['mean_absolute_deviation'] = (np.abs(phantom_masked - features_dict['mean_intensity'])).mean()
features_dict['mean_absolute_deviation']

1.5325000000000002

In [23]:
# intensity-based robust mean absolute deviation
P10_90 = phantom_masked[np.where((features_dict['tenth_percentile'] <= phantom_masked) & (phantom_masked <= features_dict['ninetenth_percentile']))] 
features_dict['robust_mean_absolute_deviation'] = (np.abs(P10_90 - P10_90.mean())).mean()
features_dict['robust_mean_absolute_deviation']

1.1138338159946537

In [24]:
# intensity-based median absolute deviation
features_dict['median_absolute_deviation'] = (np.abs(phantom_masked - features_dict['median_intensity'])).mean()
features_dict['median_absolute_deviation']

1.1375

In [25]:
# intensity-based coefficient of variation
features_dict['coefficient_of_variation'] = features_dict['intensity_variance'] / features_dict['mean_intensity']
features_dict['coefficient_of_variation']

1.5785377358490567

In [26]:
# Intensity-based quartile coefficient of dispersion
P25 = np.percentile(phantom_masked, 25)
P75 = np.percentile(phantom_masked, 75)
features_dict['quartile_coefficient_of_dispersion'] = (P75 - P25) / (P75 + P25)
features_dict['quartile_coefficient_of_dispersion']

0.6

In [27]:
# intensity based energy
features_dict['energy'] = (np.square(phantom_masked)).sum()
features_dict['energy']

567.0

In [28]:
# root mean square intensity
features_dict['root_mean_square_intensity'] = np.sqrt(features_dict['energy'] / len(phantom_masked.flatten()))
features_dict['root_mean_square_intensity']

2.662235902394827

### exporting results to a CSV file and download

In [29]:
# round results with lot of decimals up to 2 decimal
print(features_dict)
features_dict = {key : round(value, 2) for key,value in features_dict.items()}
print(features_dict)

# convert the dict to a dataframe then export it to csv format
df = pd.DataFrame(list(features_dict.items()), columns=['feature', 'value'])
df.to_csv('features.csv')


{'mean_intensity': 1.9875, 'intensity_variance': 3.1373437500000003, 'intensity_skewness': 0.6328408108841197, 'intensity kurtosis': -0.18175094675151637, 'median_intensity': 1.0, 'min_intensity': 0.0, 'tenth_percentile': 1.0, 'ninetenth_percentile': 4.0, 'max_intensity': 6.0, 'interquartile_range': 3.0, 'intensity range': 6.0, 'mean_absolute_deviation': 1.5325000000000002, 'robust_mean_absolute_deviation': 1.1138338159946537, 'median_absolute_deviation': 1.1375, 'coefficient_of_variation': 1.5785377358490567, 'quartile_coefficient_of_dispersion': 0.6, 'energy': 567.0, 'root_mean_square_intensity': 2.662235902394827}
{'mean_intensity': 1.99, 'intensity_variance': 3.14, 'intensity_skewness': 0.63, 'intensity kurtosis': -0.18, 'median_intensity': 1.0, 'min_intensity': 0.0, 'tenth_percentile': 1.0, 'ninetenth_percentile': 4.0, 'max_intensity': 6.0, 'interquartile_range': 3.0, 'intensity range': 6.0, 'mean_absolute_deviation': 1.53, 'robust_mean_absolute_deviation': 1.11, 'median_absolute_

In [30]:
# download the csv
files.download('features.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>